@host = http://localhost:3000

### read

GET {{host}}/bills

### create

POST {{host}}/bills HTTP/1.1
Content-Type: application/json

{
    "restaurant_name": "Slangin Bagels",
    "restaurant_address": "104 Ganett Dr",
    "date_receipt": "2020-06-22 19:10:25",
    "date_entered": "2020-06-22 20:25:08",
    "tax_percent": 7.5,
    "tip_percent": 25,
    "payer_id": 0
}

### update

PUT {{host}}/bills/4 HTTP/1.1
Content-Type: application/json

{
    "restaurant_name": "Slangin Bagels",
    "restaurant_address": "104 Ganett Dr",
    "date_receipt": "2020-06-22 19:10:25",
    "date_entered": "2020-06-22 20:25:08",
    "tax_percent": 7.5,
    "tip_percent": 25,
    "payer_id": 0
}

### delete

DELETE {{host}}/bills/34



### PATRONS ### -------------------------------

### read

GET {{host}}/patrons

### create

POST {{host}}/patrons HTTP/1.1
Content-Type: application/json

{
    "name_first": "Phoebe",
    "name_last": "Buffay",
    "phone": "704-555-0004"
}

### update

PUT {{host}}/patrons/0 HTTP/1.1
Content-Type: application/json

{
    "name_first": "Phoebe",
    "name_last": "Buffay",
    "phone": "704-555-0004"
}

### delete

DELETE {{host}}/patrons/0