@host = http://localhost:3000

### read

GET {{host}}/bills

### create

POST {{host}}/bills HTTP/1.1
Content-Type: application/json

{
    "restaurant": "moes" 
}

### update

PUT {{host}}/bills/4 HTTP/1.1
Content-Type: application/json

{
    "restaurant": "culvers" 
}

### delete

DELETE {{host}}/bills/7